<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- ViewVC :: http://www.viewvc.org/ -->
<head>
<title>ViewVC Exception</title>
</head>
<body>
<h3>An Exception Has Occurred</h3>

<p><pre>dompdf/wdglogo-small.gif: unknown location</pre></p>


<h4>HTTP Response Status</h4>
<p><pre>404 Not Found</pre></p>
<hr />

<h4>Python Traceback</h4>
<p><pre>
Traceback (most recent call last):
  File "/usr/local/viewvc-1.0.3.sf-new/lib/viewvc.py", line 3672, in main
    request.run_viewvc()
  File "/usr/local/viewvc-1.0.3.sf-new/lib/viewvc.py", line 329, in run_viewvc
    % self.where, '404 Not Found')
ViewVCException: 404 Not Found: dompdf/wdglogo-small.gif: unknown location

</pre></p>
</body>
</html>
